function throwError()::Nothing
    throw(ErrorException("Error occured"))
end

